#!/bin/bash
# WHAT DOES THE SUBMISSION ACTUALLY SCORE?
#
# Every P3 number reported tonight -- 86,665, 82,180, the whole table -- came from myalg_brk,
# an experimental arm generated by mkbase.  The shipped myalgorithm.py contains no reference to
# bayrepack at all, and brk's own paired control measured 96,990 / 106,700 / 106,700 on P3.
#
# So the baseline that a target of 70,000 is meant to improve on has never been measured on the
# file that is actually submitted.  That is the first thing to fix, and it is more important
# than any further P3 idea: an improvement is only an improvement against the right number.
#
# Two P3 reps, because spread is the other open question and the shipped path is the arm that
# gave 86,670 twice to the digit when it carried brk.  Then one P4 rep at its real budget, to
# have the shipped side of the pair the gate has already measured with brk on:
#
#     P4 brk on   1,981,906   ran 720 s against a 480 s budget   (+11.3%, and a 50% overrun)
#     P4 brk off  1,780,253   ran 468 s
set -u
cd "$(dirname "$0")/.." || exit 1
mkdir -p results
exec 8>"/tmp/ogc_$(basename "$0").lock"
flock -n 8 || { echo "another $(basename "$0") is already running"; exit 0; }
exec 9>/tmp/ogc_experiment.lock
flock 9 || exit 1

python3.12 -c "
import inspect, myalgorithm as S
s = inspect.getsource(S)
assert 'bayrepack' not in s, 'the shipped file DOES carry brk -- the premise of this run is wrong'
print('shipped myalgorithm.py verified: no bayrepack')" || exit 1

run () {  # prob secs tag outfile
    [ -s "results/$4" ] && return
    echo "=== $4  ($3)  $(date -u +%H:%M:%S)"
    python3.12 harness/run1.py myalgorithm "$1" "$2" "$3" > "results/$4" 2>&1
    tail -1 "results/$4"
    # PUSH, not just commit.  The container has restarted twice today and each time it
    # rewound local git to a morning snapshot and deleted every untracked file.  A local
    # commit does not survive that; a pushed one does.
    ( cd ../../.. && git add -f "research/exact_packer/session2/recon/results/$4" >/dev/null 2>&1 \
      && git commit -q -m "shipped baseline: $3" >/dev/null 2>&1 \
      && git push -q origin claude/repair-plan-model-1ig6it >/dev/null 2>&1 )
}

for rep in 1 2; do
    run 3 240 "SHIPPED P3 r$rep" "ship_p3_r${rep}.log"
done
run 4 480 "SHIPPED P4 r1" "ship_p4_r1.log"
echo "shipbase done  $(date -u +%H:%M:%S)"
